--SELECT COUNT (*) FROM TBLOGRENCILERR
--SELECT COUNT (*) AS 'TOPLAM KISI' FROM TBLOGRENCILERR WHERE OGRSEHIR='BURSA'
SELECT SUM (SINAV1) AS 'NOTLAR TOPLAMI' FROM TBLNOTLAR
SELECT AVG (SINAV1),  FROM TBLNOTLAR